# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods
  end

  desc "Push a new release build to the App Store"


  lane :test do
    increment_build_number
    scan(scheme: "GrowChildApp")
  end


  lane :release do

    increment_build_number
    sigh(force: true)
    gym(scheme: "GrowChildApp", configuration: "Release")
    deliver(force: true,
		skip_screenshots: true,
		skip_metadata: true,)
    #build_app(workspace: "GrowChildApp.xcworkspace", scheme: "GrowChildApp")
    #upload_to_app_store
  end

  lane :beta do
    increment_build_number # <= これを追加
    build_app(workspace: "GrowChildApp.xcworkspace", scheme: "GrowChildApp")
    upload_to_testflight
  end




  after_all do |lane|
    slack(
	message: "Fast Lane Success."
    )
  end

  error do |lane, exception |
    slack(
	message: exception.message,
	success: false
    )
  end

end